### ISSUE TITLE
Crash when generating world

### ISSUE THREAD

**Issue by SGZ-Creations** [Bawnorton/TrulyRandom#3]
[crash-2024-09-12_07.42.26-server.txt](https://github.com/user-attachments/files/16974102/crash-2024-09-12_07.42.26-server.txt)
[crash-2024-09-12_07.46.38-server.txt](https://github.com/user-attachments/files/16974103/crash-2024-09-12_07.46.38-server.txt)

**Comment by SGZ-Creations** [comment]
[Recipe going nuts.zip](https://github.com/user-attachments/files/16974113/Recipe.going.nuts.zip)

**Comment by Bawnorton** [comment]
Mods that add content are not supported. Remove artifacts and any others that add loot tables, recipes or items
