### ISSUE TITLE
Random Settings stick on new world.

### ISSUE THREAD

**Issue by Yuta12342** [Bawnorton/TrulyRandom#4]
While I'd love an option to save randomization seeds or presets, I think it can be a bit weird that when you have randomization on one world, and you go to create a new one, if you don't first enter the TrulyRandom GUI, the new world will retain whatever settings was in the last world you entered, so if you exit a random world, and expect to enter a fresh non-randomized world, you'll get the same randomization for the new world. I feel like the settings should internally reset when creating a new world, or after leaving the previous world, just in case.

**Comment by Bawnorton** [comment]
That should be the case; if it's not, that's a bug, I'll look into it.

**Comment by Yuta12342** [comment]
On 2.3.0, the menu would reset, but not the settings, and on 2.4.0, it seems that the menu now reflects that the settings weren't reset, which now means they need to be manually reset. It's a bit weird. Not the biggest of deals, but for people who's never used it, it might be a bit confusing.

**Comment by Bawnorton** [comment]
Fixed in 2.4.1, behaviour has been changed so that the modules are now attached directly to the world generator so it should persist and reset when expected

**Comment by Bawnorton** [comment]
Correction, I re-introduced an old bug by accident that is now fixed in 2.4.2
