### ISSUE TITLE
Fabric Server crashes when trying to generate world

### ISSUE THREAD

**Issue by jlafoy** [Bawnorton/TrulyRandom#5]
Hi! I was trying to get this working on a fabric server, and maybe I just don't know what I'm doing or it simply won't work as a server. But, here is the crash report I get when trying to spin up the server with TrulyRandom in the mods folder on the server:

[crash-2024-10-05_14.10.44-server.txt](https://github.com/user-attachments/files/17267293/crash-2024-10-05_14.10.44-server.txt)

**Comment by Bawnorton** [comment]
Dedicated servers aren't currently supported but support is planned

**Comment by Bawnorton** [comment]
2.5.3, which was just published has rudimentary server support so it won't crash.
Modules can be specified at launch with launch arguments (same place you'd put the `nogui` argument)
The arguments are in the form:
```
<module_name> <optional seed>
```
This means that if you want to enabled loot tables you'd use:
```
java -jar server.jar loot_tables
```
if you wanted to use loot tables with specify a specific seed and trades:
```
java -jar server.jar loot_tables 14253 trades
```
