### ISSUE TITLE
Game forgets tracker 

### ISSUE THREAD

**Issue by WinryGames** [Bawnorton/TrulyRandom#6]
Getting a bug where, if you play and close the game then come back to it, the tracker resets but also some of the actual drops seem to change too 

To reproduce, make a world, turn on loot tables and villager trades, play the game to unlock some of the tracker info. Close world and close game. Re-open game and world, check tracker, info should be missing

**Comment by WinryGames** [comment]
Adding onto this, it also forgets it when you die (and I have just confirmed that it definitely does completely change loot tables if you exit game and reload game

**Comment by Bawnorton** [comment]
This should have been fixed in the latest release, are you using 2.5.1?

**Comment by WinryGames** [comment]
Hi, yes I am using 2.5.1

**Comment by WinryGames** [comment]
Are there any mods that it may conflict with? I have a couple of basic ones like appleskin, dynamic lighting, inventory profiles next and xaero's maps running with it

**Comment by Bawnorton** [comment]
~~I can't replicate this in 2.5.1, so I'm going to assume that it is a mod conflict~~

Correction, I can replicate the tracker failing to save, not the drops changing however

**Comment by Bawnorton** [comment]
Should be fixed in 2.5.2; close if so

**Comment by WinryGames** [comment]
Okay I will update when 2.5.2 is out and see if the drops change - if they still do I will assume it's a mod conflict and I will figure out which one it is and let you know

**Comment by Bawnorton** [comment]
its out already https://modrinth.com/mod/trulyrandom/version/2.5.2
